import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useEffect } from 'react'

export default function Home({ list }) {


  return (
    <div className={styles.container}>
      <Head>
        <title>Contatos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tel.png" />
        
      </Head>


      <main className={styles.main}>
        <h1>
          Lista de Contatos
        </h1>

        <ul>
          {list.map(item => (
            <li>
              <a href={`/sobre/${item.id}`}>
                <img src='/tel.png' width='45'></img>
                <a>{item.name}</a> 
                <b>Tel: {item.tel}</b>


              </a>
            </li>
          ))}
        </ul>
        

        <rodape>
          <b>Pagina em modo Teste @Corporetion 2021</b>
        </rodape>

      </main>
 
    </div>
  )
}
export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/bancoDados');
  const json = await res.json();

  return {
    props: {
      list: json.list
    }
  }
}
